### ISSUE TITLE
Github credentials committed to git

### ISSUE THREAD

**Issue by mortenhauberg** [marcelobp/seekatgit#1]
Hi Marcelo,

Your credentials has been committed to git in `app/GitHub.php:41`.

I would suggest to make the repository private and change your credentials ASAP.

Regards
Morten Hauberg-Lund

**Comment by marcelobp** [comment]
Hi Morten,

Thank you very much for let me know.
It is now fixed.

Kind regards,
Marcelo

**Comment by mortenhauberg** [comment]
No problem.

It’s still visible though 
https://github.com/marcelobp/seekatgit/commit/8a909d7cf98d7b902d595c5f75cdb077578378ea#diff-12084fb7dfaa2dc6c176df1806c6909aL41 <https://github.com/marcelobp/seekatgit/commit/8a909d7cf98d7b902d595c5f75cdb077578378ea#diff-12084fb7dfaa2dc6c176df1806c6909aL41>

Med venlig hilsen
Morten Hauberg-Lund
Tlf 22 43 62 34
morten@hauberg-lund.com

**Comment by marcelobp** [comment]
I have changed my credentials. Anyway,is there any way to hide or delete
that commit log?

**Comment by mortenhauberg** [comment]
Google is your friend ;)
But I would suggest to make the repository private and changing the credentials

Med venlig hilsen
Morten Hauberg-Lund
Tlf 22 43 62 34
morten@hauberg-lund.com
